name: rosentralytics
services:
    centra:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        privileged: true
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - $HOME/.Xauthority:/root/.Xauthority
            - $HOME/ohin/ohin_ws:/home/yolo/yolo
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - DISPLAY=$DISPLAY
            - XAUTHORITY=/root/.Xauthority
        network_mode: host
        devices:
            - /dev/bus/usb
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2gb
        image: ohin112/rosentralytics:latest
        container_name: ohin_test
        command: bash