# Add udev rules for realsense devices first (if you have not done so already)
# ```bash
# echo 'SUBSYSTEM=="usb", ATTR{idVendor}=="8086", MODE="0666"' | sudo tee /etc/udev/rules.d/99-realsense-libusb.rules
# sudo udevadm control --reload-rules && udevadm trigger
# ```
name: rosentralytics
services:
    centralytics:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        privileged: true
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - $HOME/.Xauthority:/root/.Xauthority
            - $HOME/ohin/ohin_ws:/home/yolo/yolo #change the workspace path
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - DISPLAY=$DISPLAY
            - XAUTHORITY=/root/.Xauthority
        network_mode: host
        devices:
            - /dev/bus/usb
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2gb
        image: ohin112/rosentralytics:final
        container_name: final_test
        command: bash